# Copy this file to .github/workflows/ (e.g., java-matrix.yml) and modify as noted
name: Java Matrix Build Template

# Change 'main' to your branch (e.g., 'master')
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # Change to your Java versions (e.g., ['17', '21'])
        java: ['21', '25']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Change to your Java versions
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # Change 'java/pom.xml' if your pom.xml is elsewhere
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('java/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.java }}-

      # Change './java' if your project is in a different folder
      - name: Run Checkstyle
        working-directory: ./java
        run: mvn checkstyle:check
        continue-on-error: true

      # Change 'java/target/checkstyle-result.xml' if your report path differs
      - name: Upload Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report-${{ matrix.os }}-java-${{ matrix.java }}
          path: java/target/checkstyle-result.xml
          retention-days: 30

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # Change to your Java versions
        java: ['21', '25']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Change to your Java versions
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # Change 'java/pom.xml' if your pom.xml is elsewhere
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('java/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.java }}-

      # Change './java' if your project is in a different folder
      - name: Run tests
        working-directory: ./java
        run: mvn test

      # Change 'java/target/surefire-reports/' if your report path differs
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}-java-${{ matrix.java }}
          path: java/target/surefire-reports/
          retention-days: 30
